language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install Django==${DJANGO}
script: make test
env:
  - DJANGO=1.7.10
  - DJANGO=1.8.4
  - DJANGO=1.9a1
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.9a1
    - python: 3.3
      env: DJANGO=1.9a1
