language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
before_install:
  - pip install coveralls
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install Django==${DJANGO}
script: make test
env:
  - DJANGO=1.7.11
  - DJANGO=1.8.14
  - DJANGO=1.9.9
  - DJANGO=1.10.1
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.10.1
    - python: 3.3
      env: DJANGO=1.10.1
    - python: 3.2
      env: DJANGO=1.9.9
    - python: 3.3
      env: DJANGO=1.9.9
    - python: 3.5
      env: DJANGO=1.7.11
    - python: 3.5
      env: DJANGO=1.8.14
after_success:
  - coveralls
